MarketMakerArbitrageDetectorService:
    Db:
        DataConnectionString:
            settings-key: MarketMakerArbitrageDetectorService-DataConnectionString
            types:
              - AzureTableStorage
        LogsConnectionString:
            settings-key: MarketMakerArbitrageDetectorService-LogsConnString
            types:
              - AzureTableStorage
    RabbitMq:
        ConnectionString:
            settings-key: MatchingEngine-OrderBookRabbit
        Exchange:
            settings-key: LykkeOrderBooksRabbitExchangeName
        MarketMakersExchange:
            settings-key: MarketMakersPublishingRabbitExchangeName
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
AssetsServiceClient:
    ServiceUrl:
        settings-key: AssetsServiceUrl
OrderBooksCacheProviderClient:
    ServiceUrl:
        settings-key: OrderBooksCacheProviderServiceUrl